### ISSUE TITLE
Songs are not synchronized with spotify to start at the same time, apparently because slow internet issues

### ISSUE THREAD

**Issue by Shinkei** [TFFLabs/SoundFoundry#60]
When the app sends the event to spotify, it takes some seconds to start but the app is already those seconds ahead, this is more evident when the internet is slow because the gap is bigger.

**Comment by Efgar** [comment]
This is a though one, some work has been done and need to be tested, will see how it goes

**Comment by adrianmoya** [comment]
Maybe this can be syncronized via a ready-to-listen event? (Crazy idea)

**Comment by Efgar** [comment]
Seems fixed now, have in mind we have an intentional 1% error margin to switch songs
